name: .NET CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v4

    - name: .NET kur
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Bağımlılıkları yükle
      run: dotnet restore WebApplication1.sln

    - name: Projeyi derle
      run: dotnet build WebApplication1.sln --no-restore --configuration Release

    - name: Testleri çalıştır
      run: dotnet test WebApplication1.sln --no-build --configuration Release
